services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - ./.env
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      # N8N_HOST / WEBHOOK_URL / N8N_WEBHOOK_URL pueden definirse en .env
    volumes:
      - ./n8n-data:/home/node/.n8n

  n8n-worker:
    image: n8nio/n8n
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    environment:
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
    entrypoint: ["/usr/local/bin/node", "/usr/local/lib/node_modules/n8n/bin/n8n"]
    command: ["worker"]

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
      - POSTGRES_DB=n8n
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    volumes:
      - ./redis-data:/data